### ISSUE TITLE
Investigate and / or fix 5 failing tests on Android

### ISSUE THREAD

**Issue by akinwale** [lbryio/lbry-android#11]
### Failed tests
- tests.unit.core.test_log_support.TestLogger.test_can_log_failure 
- tests.unit.lbrynet_daemon.test_ExchangeRateManager.ExchangeRateTest.test_invalid_rates
- tests.unit.test_conf.SettingsTest.test_invalid_data_type_raises_exception
- tests.unit.test_conf.SettingsTest.test_invalid_setting_raises_exception
- tests.unit.lbrynet_daemon.test_Daemon.TestJsonRpc.test_help

### Failure logs
```
09-18 09:18:01.770 16289-16308/io.lbry.lbrynet:service_lbrynet_testrunner I/testrunnerservice: ===============================================================================
09-18 09:18:01.770 16289-16308/io.lbry.lbrynet:service_lbrynet_testrunner I/testrunnerservice: [FAIL]
09-18 09:18:01.770 16289-16308/io.lbry.lbrynet:service_lbrynet_testrunner I/testrunnerservice: Traceback (most recent call last):
09-18 09:18:01.770 16289-16308/io.lbry.lbrynet:service_lbrynet_testrunner I/testrunnerservice:   File "/home/akinwale/Dev/Python/lbry-android/.buildozer/android/platform/build/dists/lbrynet/private/lib/python2.7/site-packages/tests/unit/core/test_log_support.py", line 40, in <lambda>
09-18 09:18:01.770 16289-16308/io.lbry.lbrynet:service_lbrynet_testrunner I/testrunnerservice:     
09-18 09:18:01.770 16289-16308/io.lbry.lbrynet:service_lbrynet_testrunner I/testrunnerservice:   File "/home/akinwale/Dev/Python/lbry-android/.buildozer/android/platform/build/dists/lbrynet/private/lib/python2.7/site-packages/twisted/trial/_synctest.py", line 425, in assertEqual
09-18 09:18:01.770 16289-16308/io.lbry.lbrynet:service_lbrynet_testrunner I/testrunnerservice:     
09-18 09:18:01.770 16289-16308/io.lbry.lbrynet:service_lbrynet_testrunner I/testrunnerservice:   File "/home/akinwale/Dev/Python/lbry-android/.buildozer/android/platform/build/dists/lbrynet/private/lib/python2.7/unittest/case.py", line 513, in assertEqual
09-18 09:18:01.770 16289-16308/io.lbry.lbrynet:service_lbrynet_testrunner I/testrunnerservice:     
09-18 09:18:01.770 16289-16308/io.lbry.lbrynet:service_lbrynet_testrunner I/testrunnerservice:   File "/home/akinwale/Dev/Python/lbry-android/.buildozer/android/platform/build/dists/lbrynet/private/lib/python2.7/unittest/case.py", line 506, in _baseAssertEqual
09-18 09:18:01.770 16289-16308/io.lbry.lbrynet:service_lbrynet_testrunner I/testrunnerservice:     
09-18 09:18:01.770 16289-16308/io.lbry.lbrynet:service_lbrynet_testrunner I/testrunnerservice: twisted.trial.unittest.FailTest: 'test_log_support.py:18 - My message: terrible things happened' != 'log_support.py:353 - My message: terrible things happened'
09-18 09:18:01.770 16289-16308/io.lbry.lbrynet:service_lbrynet_testrunner I/testrunnerservice: tests.unit.core.test_log_support.TestLogger.test_can_log_failure
09-18 09:18:01.770 16289-16308/io.lbry.lbrynet:service_lbrynet_testrunner I/testrunnerservice: ===============================================================================
09-18 09:18:01.770 16289-16308/io.lbry.lbrynet:service_lbrynet_testrunner I/testrunnerservice: [FAIL]
09-18 09:18:01.770 16289-16308/io.lbry.lbrynet:service_lbrynet_testrunner I/testrunnerservice: Traceback (most recent call last):
09-18 09:18:01.770 16289-16308/io.lbry.lbrynet:service_lbrynet_testrunner I/testrunnerservice:   File "/home/akinwale/Dev/Python/lbry-android/.buildozer/android/platform/build/dists/lbrynet/private/lib/python2.7/site-packages/tests/unit/lbrynet_daemon/test_ExchangeRateManager.py", line 39, in test_invalid_rates
09-18 09:18:01.770 16289-16308/io.lbry.lbrynet:service_lbrynet_testrunner I/testrunnerservice:     
09-18 09:18:01.770 16289-16308/io.lbry.lbrynet:service_lbrynet_testrunner I/testrunnerservice:   File "/home/akinwale/Dev/Python/lbry-android/.buildozer/android/platform/build/dists/lbrynet/private/lib/python2.7/site-packages/twisted/trial/_synctest.py", line 324, in __exit__
09-18 09:18:01.770 16289-16308/io.lbry.lbrynet:service_lbrynet_testrunner I/testrunnerservice:     
09-18 09:18:01.770 16289-16308/io.lbry.lbrynet:service_lbrynet_testrunner I/testrunnerservice: twisted.trial.unittest.FailTest: AssertionError not raised (None returned)
09-18 09:18:01.770 16289-16308/io.lbry.lbrynet:service_lbrynet_testrunner I/testrunnerservice: tests.unit.lbrynet_daemon.test_ExchangeRateManager.ExchangeRateTest.test_invalid_rates
09-18 09:18:01.770 16289-16308/io.lbry.lbrynet:service_lbrynet_testrunner I/testrunnerservice: ===============================================================================
09-18 09:18:01.770 16289-16308/io.lbry.lbrynet:service_lbrynet_testrunner I/testrunnerservice: [FAIL]
09-18 09:18:01.770 16289-16308/io.lbry.lbrynet:service_lbrynet_testrunner I/testrunnerservice: Traceback (most recent call last):
09-18 09:18:01.770 16289-16308/io.lbry.lbrynet:service_lbrynet_testrunner I/testrunnerservice:   File "/home/akinwale/Dev/Python/lbry-android/.buildozer/android/platform/build/dists/lbrynet/private/lib/python2.7/site-packages/tests/unit/test_conf.py", line 47, in test_invalid_data_type_raises_exception
09-18 09:18:01.770 16289-16308/io.lbry.lbrynet:service_lbrynet_testrunner I/testrunnerservice:     
09-18 09:18:01.770 16289-16308/io.lbry.lbrynet:service_lbrynet_testrunner I/testrunnerservice:   File "/home/akinwale/Dev/Python/lbry-android/.buildozer/android/platform/build/dists/lbrynet/private/lib/python2.7/site-packages/twisted/trial/_synctest.py", line 414, in assertRaises
09-18 09:18:01.770 16289-16308/io.lbry.lbrynet:service_lbrynet_testrunner I/testrunnerservice:     
09-18 09:18:01.770 16289-16308/io.lbry.lbrynet:service_lbrynet_testrunner I/testrunnerservice:   File "/home/akinwale/Dev/Python/lbry-android/.buildozer/android/platform/build/dists/lbrynet/private/lib/python2.7/site-packages/twisted/trial/_synctest.py", line 308, in _handle
09-18 09:18:01.770 16289-16308/io.lbry.lbrynet:service_lbrynet_testrunner I/testrunnerservice:     
09-18 09:18:01.770 16289-16308/io.lbry.lbrynet:service_lbrynet_testrunner I/testrunnerservice:   File "/home/akinwale/Dev/Python/lbry-android/.buildozer/android/platform/build/dists/lbrynet/private/lib/python2.7/site-packages/twisted/trial/_synctest.py", line 346, in __exit__
09-18 09:18:01.770 16289-16308/io.lbry.lbrynet:service_lbrynet_testrunner I/testrunnerservice:     
09-18 09:18:01.770 16289-16308/io.lbry.lbrynet:service_lbrynet_testrunner I/testrunnerservice: twisted.trial.unittest.FailTest: exceptions.KeyError raised instead of AssertionError:
09-18 09:18:01.770 16289-16308/io.lbry.lbrynet:service_lbrynet_testrunner I/testrunnerservice:  Traceback (most recent call last):
09-18 09:18:01.770 16289-16308/io.lbry.lbrynet:service_lbrynet_testrunner I/testrunnerservice:   File "/home/akinwale/Dev/Python/lbry-android/.buildozer/android/platform/build/dists/lbrynet/private/lib/python2.7/site-packages/twisted/internet/utils.py", line 197, in runWithWarningsSuppressed
09-18 09:18:01.770 16289-16308/io.lbry.lbrynet:service_lbrynet_testrunner I/testrunnerservice:     
09-18 09:18:01.770 16289-16308/io.lbry.lbrynet:service_lbrynet_testrunner I/testrunnerservice:   File "/home/akinwale/Dev/Python/lbry-android/.buildozer/android/platform/build/dists/lbrynet/private/lib/python2.7/site-packages/tests/unit/test_conf.py", line 47, in test_invalid_data_type_raises_exception
09-18 09:18:01.770 16289-16308/io.lbry.lbrynet:service_lbrynet_testrunner I/testrunnerservice:     
09-18 09:18:01.770 16289-16308/io.lbry.lbrynet:service_lbrynet_testrunner I/testrunnerservice:   File "/home/akinwale/Dev/Python/lbry-android/.buildozer/android/platform/build/dists/lbrynet/private/lib/python2.7/site-packages/twisted/trial/_synctest.py", line 414, in assertRaises
09-18 09:18:01.770 16289-16308/io.lbry.lbrynet:service_lbrynet_testrunner I/testrunnerservice:     
09-18 09:18:01.770 16289-16308/io.lbry.lbrynet:service_lbrynet_testrunner I/testrunnerservice:   File "/home/akinwale/Dev/Python/lbry-android/.buildozer/android/platform/build/dists/lbrynet/private/lib/python2.7/site-packages/twisted/trial/_synctest.py", line 308, in _handle
09-18 09:18:01.770 16289-16308/io.lbry.lbrynet:service_lbrynet_testrunner I/testrunnerservice:     
09-18 09:18:01.770 16289-16308/io.lbry.lbrynet:service_lbrynet_testrunner I/testrunnerservice: --- <exception caught here> ---
09-18 09:18:01.771 16289-16308/io.lbry.lbrynet:service_lbrynet_testrunner I/testrunnerservice:   File "/home/akinwale/Dev/Python/lbry-android/.buildozer/android/platform/build/dists/lbrynet/private/lib/python2.7/site-packages/twisted/trial/_synctest.py", line 308, in _handle
09-18 09:18:01.771 16289-16308/io.lbry.lbrynet:service_lbrynet_testrunner I/testrunnerservice:     
09-18 09:18:01.771 16289-16308/io.lbry.lbrynet:service_lbrynet_testrunner I/testrunnerservice:   File "/home/akinwale/Dev/Python/lbry-android/.buildozer/android/platform/build/dists/lbrynet/private/lib/python2.7/site-packages/twisted/trial/_synctest.py", line 414, in <lambda>
09-18 09:18:01.771 16289-16308/io.lbry.lbrynet:service_lbrynet_testrunner I/testrunnerservice:     
09-18 09:18:01.771 16289-16308/io.lbry.lbrynet:service_lbrynet_testrunner I/testrunnerservice:   File "/home/akinwale/Dev/Python/lbry-android/.buildozer/android/platform/build/dists/lbrynet/private/lib/python2.7/site-packages/lbrynet/conf.py", line 425, in set
09-18 09:18:01.771 16289-16308/io.lbry.lbrynet:service_lbrynet_testrunner I/testrunnerservice:     
09-18 09:18:01.771 16289-16308/io.lbry.lbrynet:service_lbrynet_testrunner I/testrunnerservice: exceptions.KeyError: 'fake_data_type'
09-18 09:18:01.771 16289-16308/io.lbry.lbrynet:service_lbrynet_testrunner I/testrunnerservice: tests.unit.test_conf.SettingsTest.test_invalid_data_type_raises_exception
09-18 09:18:01.771 16289-16308/io.lbry.lbrynet:service_lbrynet_testrunner I/testrunnerservice: ===============================================================================
09-18 09:18:01.771 16289-16308/io.lbry.lbrynet:service_lbrynet_testrunner I/testrunnerservice: [FAIL]
09-18 09:18:01.771 16289-16308/io.lbry.lbrynet:service_lbrynet_testrunner I/testrunnerservice: Traceback (most recent call last):
09-18 09:18:01.771 16289-16308/io.lbry.lbrynet:service_lbrynet_testrunner I/testrunnerservice:   File "/home/akinwale/Dev/Python/lbry-android/.buildozer/android/platform/build/dists/lbrynet/private/lib/python2.7/site-packages/tests/unit/test_conf.py", line 42, in test_invalid_setting_raises_exception
09-18 09:18:01.771 16289-16308/io.lbry.lbrynet:service_lbrynet_testrunner I/testrunnerservice:     
09-18 09:18:01.771 16289-16308/io.lbry.lbrynet:service_lbrynet_testrunner I/testrunnerservice:   File "/home/akinwale/Dev/Python/lbry-android/.buildozer/android/platform/build/dists/lbrynet/private/lib/python2.7/site-packages/twisted/trial/_synctest.py", line 414, in assertRaises
09-18 09:18:01.771 16289-16308/io.lbry.lbrynet:service_lbrynet_testrunner I/testrunnerservice:     
09-18 09:18:01.771 16289-16308/io.lbry.lbrynet:service_lbrynet_testrunner I/testrunnerservice:   File "/home/akinwale/Dev/Python/lbry-android/.buildozer/android/platform/build/dists/lbrynet/private/lib/python2.7/site-packages/twisted/trial/_synctest.py", line 308, in _handle
09-18 09:18:01.771 16289-16308/io.lbry.lbrynet:service_lbrynet_testrunner I/testrunnerservice:     
09-18 09:18:01.771 16289-16308/io.lbry.lbrynet:service_lbrynet_testrunner I/testrunnerservice:   File "/home/akinwale/Dev/Python/lbry-android/.buildozer/android/platform/build/dists/lbrynet/private/lib/python2.7/site-packages/twisted/trial/_synctest.py", line 324, in __exit__
09-18 09:18:01.771 16289-16308/io.lbry.lbrynet:service_lbrynet_testrunner I/testrunnerservice:     
09-18 09:18:01.771 16289-16308/io.lbry.lbrynet:service_lbrynet_testrunner I/testrunnerservice: twisted.trial.unittest.FailTest: AssertionError not raised (None returned)
09-18 09:18:01.771 16289-16308/io.lbry.lbrynet:service_lbrynet_testrunner I/testrunnerservice: tests.unit.test_conf.SettingsTest.test_invalid_setting_raises_exception
09-18 09:18:01.771 16289-16308/io.lbry.lbrynet:service_lbrynet_testrunner I/testrunnerservice: ===============================================================================
09-18 09:18:01.780 16289-16308/io.lbry.lbrynet:service_lbrynet_testrunner I/testrunnerservice: [ERROR]
09-18 09:18:01.780 16289-16308/io.lbry.lbrynet:service_lbrynet_testrunner I/testrunnerservice: Traceback (most recent call last):
09-18 09:18:01.780 16289-16308/io.lbry.lbrynet:service_lbrynet_testrunner I/testrunnerservice:   File "/home/akinwale/Dev/Python/lbry-android/.buildozer/android/platform/build/dists/lbrynet/private/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
09-18 09:18:01.780 16289-16308/io.lbry.lbrynet:service_lbrynet_testrunner I/testrunnerservice:     
09-18 09:18:01.780 16289-16308/io.lbry.lbrynet:service_lbrynet_testrunner I/testrunnerservice:   File "/home/akinwale/Dev/Python/lbry-android/.buildozer/android/platform/build/dists/lbrynet/private/lib/python2.7/site-packages/lbrynet/daemon/Daemon.py", line 1178, in jsonrpc_help
09-18 09:18:01.780 16289-16308/io.lbry.lbrynet:service_lbrynet_testrunner I/testrunnerservice:     
09-18 09:18:01.780 16289-16308/io.lbry.lbrynet:service_lbrynet_testrunner I/testrunnerservice:   File "/home/akinwale/Dev/Python/lbry-android/.buildozer/android/platform/build/build/other_builds/python2-openssl-sqlite3/armeabi-v7a/python2/python-install/lib/python2.7/textwrap.py", line 390, in dedent
09-18 09:18:01.780 16289-16308/io.lbry.lbrynet:service_lbrynet_testrunner I/testrunnerservice:     
09-18 09:18:01.780 16289-16308/io.lbry.lbrynet:service_lbrynet_testrunner I/testrunnerservice: exceptions.TypeError: expected string or buffer
09-18 09:18:01.780 16289-16308/io.lbry.lbrynet:service_lbrynet_testrunner I/testrunnerservice: tests.unit.lbrynet_daemon.test_Daemon.TestJsonRpc.test_help
09-18 09:18:01.780 16289-16308/io.lbry.lbrynet:service_lbrynet_testrunner I/testrunnerservice: -------------------------------------------------------------------------------
09-18 09:18:01.780 16289-16308/io.lbry.lbrynet:service_lbrynet_testrunner I/testrunnerservice: Ran 113 tests in 62.488s
```

**Comment by akinwale** [comment]
**tests.unit.core.test_log_support.TestLogger.test_can_log_failure**
```
09-18 09:18:01.770 16289-16308/io.lbry.lbrynet:service_lbrynet_testrunner I/testrunnerservice: twisted.trial.unittest.FailTest: 'test_log_support.py:18 - My message: terrible things happened' != 'log_support.py:353 - My message: terrible things happened'
```
The filename and line number mismatch between the expected and actual messages may be happening due to the fact that the tests are loaded as a compiled package on the Android platform.

**tests.unit.test_conf.SettingsTest.test_invalid_data_type_raises_exception**
`KeyError` is raised because the `"fake_data_type"` key is not found in the `Config` class' `_data` member. This may also be due to the tests being loaded as a compiled package on the Android platform.

**tests.unit.lbrynet_daemon.test_ExchangeRateManager.ExchangeRateTest.test_invalid_rates
tests.unit.test_conf.SettingsTest.test_invalid_setting_raises_exception**
The `assert` statements in the Python code don't seem to be working which results in the corresponding `AssertionError` not being raised. Proposed fix would be to explicitly check the conditions and raise the `AssertionError`. 
 
**tests.unit.lbrynet_daemon.test_Daemon.TestJsonRpc.test_help**
Still haven't been able to figure out why this is failing.

**Comment by akinwale** [comment]
Fixed 3, skipped 2 due to no fix. https://github.com/lbryio/lbry/pull/940
