### ISSUE TITLE
crash on search term + enter - maybe repost?

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#1116]
searching electroboom and then clicking enter crashes the app. There is a repost at this URL, so that could be it. 
```
2021-01-11 11:50:38.025 28171-28171/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.lbry.browser, PID: 28171
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String io.lbry.browser.model.Claim.getName()' on a null object reference
        at io.lbry.browser.adapter.ClaimListAdapter.onBindViewHolder(ClaimListAdapter.java:407)
        at io.lbry.browser.adapter.ClaimListAdapter.onBindViewHolder(ClaimListAdapter.java:35)
        at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7065)
        at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
        at android.view.View.layout(View.java:22085)
        at android.view.ViewGroup.layout(ViewGroup.java:6290)
        at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1855)
        at android.view.View.layout(View.java:22085)
        at android.view.ViewGroup.layout(ViewGroup.java:6290)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:22085)
        at android.view.ViewGroup.layout(ViewGroup.java:6290)
        at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1855)
        at android.view.View.layout(View.java:22085)
        at android.view.ViewGroup.layout(ViewGroup.java:6290)
        at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:148)
        at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:43)
        at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1996)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:918)
        at android.view.View.layout(View.java:22085)
        at android.view.ViewGroup.layout(ViewGroup.java:6290)
        at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1263)
        at android.view.View.layout(View.java:22085)
        at android.view.ViewGroup.layout(ViewGroup.java:6290)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:22085)
        at android.view.ViewGroup.layout(ViewGroup.java:6290)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:22085)
        at android.view.ViewGroup.layout(ViewGroup.java:6290)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:22085)
        at android.view.ViewGroup.layout(ViewGroup.java:6290)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
        at android.view.View.layout(View.java:22085)
2021-01-11 11:50:38.052 1297-5490/? W/ActivityTaskManager:   Force finishing activity io.lbry.browser/.MainActivity
2021-01-11 11:50:38.054 1297-3853/? D/FrameworkEventCollector: recordAppIssue PN: io.lbry.browser
2021-01-11 11:50:38.169 1297-1978/? W/InputDispatcher: channel '8949aa2 io.lbry.browser/io.lbry.browser.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
2021-01-11 11:50:38.169 1297-1978/? E/InputDispatcher: channel '8949aa2 io.lbry.browser/io.lbry.browser.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
2021-01-11 11:50:38.175 1297-4565/? I/WindowManager: WIN DEATH: Window{8949aa2 u0 io.lbry.browser/io.lbry.browser.MainActivity}
2021-01-11 11:50:38.175 1297-4565/? W/InputDispatcher: Attempted to unregister already unregistered input channel '8949aa2 io.lbry.browser/io.lbry.browser.MainActivity (server)'
2021-01-11 11:50:38.187 1297-5188/? I/ActivityManager: Process io.lbry.browser (pid 28171) has died: vis+99 TOP 
2021-01-11 11:50:38.259 20862-20862/? D/FrequentAppsGrid: App icon adds to Shelf: ComponentInfo{io.lbry.browser/io.lbry.browser.MainActivity}```

**Comment by akinwale** [comment]
Fixed in https://github.com/lbryio/lbry-android/commit/e1d51c881a96cce5e649899e4013a37336823c2d
