### ISSUE TITLE
Can not build app

### ISSUE THREAD

**Issue by oakey22** [lbryio/lbry-android#37]
I have been trying for 2 days now to get it to build, the steps i do are
clone lbry-android
cope the buildozer.spec.sample to buildozer.spec
then build the app.

i get this error:

```
[INFO]:    Selecting java build tool:
[INFO]:    Detected highest available build tools version to be 23.0.1
[INFO]:        Building with ant, as the highest build-tools-version is only 23.0.1
[DEBUG]:   -> running ant debug
[DEBUG]:   	Buildfile: /home/shift/lbry-android/.buildozer/android/platform/build/dists/lbrynet/build.xml
[DEBUG]:   	
[DEBUG]:   	-set-mode-check:
[DEBUG]:   	
[DEBUG]:   	-set-debug-files:
[DEBUG]:   	
[DEBUG]:   	-check-env:
[DEBUG]:   	 [checkenv] Android SDK Tools Revision 24.0.0
[DEBUG]:   	 [checkenv] Installed at /home/shift/.buildozer/android/platform/android-sdk-24
[DEBUG]:   	
[DEBUG]:   	-setup:
[DEBUG]:   	     [echo] Project Name: lbrynet-0.1
[DEBUG]:   	  [gettype] Project Type: Application
[DEBUG]:   	
[DEBUG]:   	-set-debug-mode:
[DEBUG]:   	
[DEBUG]:   	-debug-obfuscation-check:
[DEBUG]:   	
[DEBUG]:   	-pre-build:
[DEBUG]:   	     [copy] Copying 27 files to /home/shift/lbry-android/.buildozer/android/platform/build/dists/lbrynet/tmp-src
[DEBUG]:   	
[DEBUG]:   	-build-setup:
[DEBUG]:   	[getbuildtools] Using latest Build Tools: 23.0.1
[DEBUG]:   	     [echo] Resolving Build Target for lbrynet-0.1...
[DEBUG]:   	[gettarget] Project Target:   Android 6.0
[DEBUG]:   	[gettarget] API level:        23
[DEBUG]:   	     [echo] ----------
[DEBUG]:   	     [echo] Creating output directories if needed...
[DEBUG]:   	    [mkdir] Created dir: /home/shift/lbry-android/.buildozer/android/platform/build/dists/lbrynet/bin/rsObj
[DEBUG]:   	    [mkdir] Created dir: /home/shift/lbry-android/.buildozer/android/platform/build/dists/lbrynet/bin/rsLibs
[DEBUG]:   	     [echo] ----------
[DEBUG]:   	     [echo] Resolving Dependencies for lbrynet-0.1...
[DEBUG]:   	[dependency] Library dependencies:
[DEBUG]:   	[dependency] No Libraries
[DEBUG]:   	[dependency]
[DEBUG]:   	[dependency] ------------------
[DEBUG]:   	     [echo] ----------
[DEBUG]:   	     [echo] Building Libraries with 'debug'...
[DEBUG]:   	   [subant] No sub-builds to iterate on
[DEBUG]:   	
[DEBUG]:   	-code-gen:
[DEBUG]:   	[mergemanifest] Found modified input file
[DEBUG]:   	[mergemanifest] Merging AndroidManifest files into one.
[DEBUG]:   	[mergemanifest] Manifest merger disabled. Using project manifest only.
[DEBUG]:   	     [echo] Handling aidl files...
[DEBUG]:   	     [aidl] No AIDL files to compile.
[DEBUG]:   	     [echo] ----------
[DEBUG]:   	     [echo] Handling RenderScript files...
[DEBUG]:   	     [echo] ----------
[DEBUG]:   	     [echo] Handling Resources...
[DEBUG]:   	     [aapt] Generating resource IDs...
[DEBUG]:   	     [aapt]     (skipping file '.gitkeep' due to ANDROID_AAPT_IGNORE pattern '.*')
[DEBUG]:   	     [aapt] /home/shift/lbry-android/.buildozer/android/platform/build/dists/lbrynet/bin/AndroidManifest.xml:73: error: Error: No resource found that matches the given name (at 'theme' with value '@style/Theme.AppCompat.Light.NoActionBar').
[DEBUG]:   	     [aapt]
[DEBUG]:   	
[DEBUG]:   	BUILD FAILED
[DEBUG]:   	/home/shift/.buildozer/android/platform/android-sdk-24/tools/ant/build.xml:653: The following error occurred while executing this line:
[DEBUG]:   	/home/shift/.buildozer/android/platform/android-sdk-24/tools/ant/build.xml:698: null returned: 1
[DEBUG]:   	
[DEBUG]:   	Total time: 0 seconds
Exception in thread background thread for pid 21638:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/shift/.local/lib/python2.7/site-packages/sh.py", line 2170, in background_thread
    handle_exit_code(exit_code)
  File "/home/shift/.local/lib/python2.7/site-packages/sh.py", line 1929, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/home/shift/.local/lib/python2.7/site-packages/sh.py", line 672, in handle_command_exit_code
    raise exc
ErrorReturnCode_1: 

  RAN: /home/shift/.buildozer/android/platform/apache-ant-1.9.4/bin/ant debug

  STDOUT:
Buildfile: /home/shift/lbry-android/.buildozer/android/platform/build/dists/lbrynet/build.xml

-set-mode-check:

-set-debug-files:

-check-env:
 [checkenv] Android SDK Tools Revision 24.0.0
 [checkenv] Installed at /home/shift/.buildozer/android/platform/android-sdk-24

-setup:
     [echo] Project Name: lbrynet-0.1
  [gettype] Project Type: Application

-set-debug-mode:

-debug-obfuscation-check:

-pre-build:
     [copy] Copying 27 files to /home/shift/lbry-android/.buildozer/android/platform/build/dists/lbrynet/tmp-src

-build-setup:
[getbuildtools] Using latest Build Tools: 23.0.1
     [echo] Resolving Build Target for lbrynet-0.1...
[gettarget] Project Target:   Android 6.0
[gettarget] API level:        23
     [echo] ----------
     [echo] Creating output directories if needed...
    [mkdir] Created dir: /home/shift/lbry-android/.buildozer/android/platform/build/dists/lbrynet/bin/rsObj
    [mkdir] Created dir: /home/shift/lbry-android/.buildozer/android/platform/build/dists/lbrynet/bin/rsLibs
     [echo] ----------
     [echo] Resolving Dependencies for lbrynet-0.1...
[dependency] Library dependencies:
[dependency] No Libraries
[dependency] 
[dependency] ------------------
     [echo] ----------
     [echo] Building Libraries with 'debug'...
   [subant] No sub-builds to iterate on

-code-gen:
[mergemanifest] Found modified input file
[mergemanifest] Merging AndroidManifest files into one.
[mergemanifest] Manifest merger disabled. Using project manifest only.
     [echo] Handling aidl files...
     [aidl] No AIDL files to compile.
     [echo] ----------
     [echo] Handling RenderScript files...
     [echo] ----------
     [echo] Handling Resources...
     [aapt] Generating resource IDs...
     [aapt]     (skipping file '.gitkeep' due to ANDROID_AAPT_IGNORE pattern '.*')
     [aapt] /home/shift/lbry-android/.buildozer/android/platform/build/dists/lbrynet/bin/AndroidManifest.xml:73: error: Error: No resource found that matches the given name (at 'theme' with value '@style/Theme.AppCompat.Light.NoActionBar').
     [aapt] 

BUILD FAILED
/home/shift/.buildozer/android/platform/android-sdk-24/tools/ant/build.xml:653: The following error occurred while executing this line:
/home/shift/.buildozer/android/platform/android-sdk-24/tools/ant/build.xml:698: null returned: 1

Total time: 0 seconds


  STDERR:


[INFO]:    STDOUT (last 20 lines of 60):
	-code-gen:	
[mergemanifest] Found modified input file	
[mergemanifest] Merging AndroidManifest files into one.	
[mergemanifest] Manifest merger disabled. Using project manifest only.	
     [echo] Handling aidl files...	
     [aidl] No AIDL files to compile.	
     [echo] ----------	
     [echo] Handling RenderScript files...	
     [echo] ----------	
     [echo] Handling Resources...	
     [aapt] Generating resource IDs...	
     [aapt]     (skipping file '.gitkeep' due to ANDROID_AAPT_IGNORE pattern '.*')	
     [aapt] /home/shift/lbry-android/.buildozer/android/platform/build/dists/lbrynet/bin/AndroidManifest.xml:73: error: Error: No resource found that matches the given name (at 'theme' with value '@style/Theme.AppCompat.Light.NoActionBar').	
     [aapt] 	
	
BUILD FAILED	
/home/shift/.buildozer/android/platform/android-sdk-24/tools/ant/build.xml:653: The following error occurred while executing this line:	
/home/shift/.buildozer/android/platform/android-sdk-24/tools/ant/build.xml:698: null returned: 1	
	
Total time: 0 seconds
[INFO]:    STDERR:
	
[INFO]:    COMMAND:
cd /home/shift/lbry-android/.buildozer/android/platform/build/dists/lbrynet && /home/shift/.buildozer/android/platform/apache-ant-1.9.4/bin/ant debug

[WARNING]: ERROR: /home/shift/.buildozer/android/platform/apache-ant-1.9.4/bin/ant failed!
# Command failed: /usr/bin/python2.7 -m pythonforandroid.toolchain apk --debug --bootstrap=lbry --dist_name lbrynet --name lbrynet --version 0.1 --package io.lbry.lbrynet --android_api 23 --minsdk 16 --private /home/shift/lbry-android/.buildozer/android/app --permission INTERNET --permission READ_EXTERNAL_STORAGE --permission WRITE_EXTERNAL_STORAGE --orientation portrait --window --service lbrynetservice:./lbrynetservice.py --copy-libs --local-recipes /home/shift/lbry-android/recipes --depend com.android.support:appcompat-v7:23.4.0 --depend com.facebook.react:react-native:+ --arch armeabi-v7a --color=always --storage-dir=/home/shift/lbry-android/.buildozer/android/platform/build
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2
```

**Comment by oakey22** [comment]
oh i did try sdk 23 too and that failed. The above error was the same for both 23 (default) and 24

**Comment by akinwale** [comment]
@oakey22 You'll need to install buildozer from https://github.com/akinwale/buildozer
Had to fork buildozer in order to allow the React source files to be copied along with the Java and Python source.

You can do this using the following commands.
```
git clone https://github.com/akinwale/buildozer
cd buildozer
python setup.py build
sudo pip install -e .
```

Once this is done, try the build again. Also, make sure you're using the the latest `buildozer.spec.sample` as your `buildozer.spec`.

**Comment by oakey22** [comment]
still getting the same error. after rebuilding it with your buildozer.

**Comment by akinwale** [comment]
Try with the following settings in your `buildozer.spec`
android.api = 26
android.sdk = 26

If this doesn't work, you may have to unpack Android build tools 26.0.1 into your Android SDK directory. You can check the `.travis.yml` file for steps on how to do this.

**Comment by oakey22** [comment]
Manually doing the install with the steps in travis.yml i was able to build it. Thanks

**Comment by akinwale** [comment]
Great. I'll be updating the build documentation soon, as there have been a lot of updates since the first doc was written.
