### ISSUE TITLE
Android 5.0.1 doesn't support correct permissions for wallet

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#584]
## The Issue
Had a user with 5.0.1 run the app and he does not get a prompt for permissions. Changing permissions on the app itself does not seem to help. We should probably disable LBRY for 5.0.1 and only support anything higher or when these permissions actually work.

What's strange is that blocks do come in, but the wallet can't be accessed. Even after restart ,the wallet component does not load. 

```
2019-06-16 18:13:44,751 INFO     lbrynet.extras.daemon.Components:266: Starting torba wallet
2019-06-16 18:13:44,759 INFO     lbrynet.wallet.manager:153: Wallet at /storage/emulated/0/Android/data/io.lbry.browser/files/lbryum/wallets/default_wallet is empty, generating a default account.
2019-06-16 18:13:45,603 ERROR    lbrynet.extras.daemon.Component:61: Error setting up wallet
Traceback (most recent call last):
  File "/data/data/io.lbry.browser/files/app/crystax_python/site-packages/lbrynet/extras/daemon/Component.py", line 55, in _setup
    result = await self.start()
  File "/data/data/io.lbry.browser/files/app/crystax_python/site-packages/lbrynet/extras/daemon/Components.py", line 267, in start
    self.wallet_manager = await LbryWalletManager.from_lbrynet_config(self.conf)
  File "/data/data/io.lbry.browser/files/app/crystax_python/site-packages/lbrynet/wallet/manager.py", line 155, in from_lbrynet_config
    manager.default_wallet.save()
  File "/data/data/io.lbry.browser/files/app/crystax_python/site-packages/torba/client/wallet.py", line 55, in save
    self.storage.write(self.to_dict())
  File "/data/data/io.lbry.browser/files/app/crystax_python/site-packages/torba/client/wallet.py", line 136, in write
    os.chmod(self.path, mode)
PermissionError: [Errno 1] Operation not permitted: '/storage/emulated/0/Android/data/io.lbry.browser/files/lbryum/wallets/default_wallet'
```

## System Configuration
- Device:
- Android version:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by kauffj** [comment]
We're not going to focus on supporting anything earlier than 6.x unless it is very easy to fix.

If you can give reproduction for this we might fix it, please re-open if you can.
