### ISSUE TITLE
wallet locked after account sync/restore

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#657]
When restoring wallets with lots of accounts (happens for users who sign back in often, since a new account is added each time), there's a chance that the wallet stays locked. This sounds like a timing issue and because we don't check the success status of the unlock.

Sync apply should run first, then we set the default account, and then we should call unlock. After unlock is called, the status of the wallet should be checked to make sure it was unlocked. And if not, attempt to unlock again.

**Comment by tzarebczan** [comment]
Fixed in 0.8.4

**Comment by tzarebczan** [comment]
Reopening because there are still some cases where the wallet is locked.  

The below example is with a blank password. I was not able to reproduce. He originally synced his account and sent a transaction - so the wallet was unlocked then but not after a restart. 

We should confirm the wallet is unlocked from the status call. 

```2019-09-10 20:29:38,424 INFO     lbry.wallet.ledger:105: Loaded account bS7RKbhBwcbLgzaJAsBP5DioTzhzQyFVgi with 0.999802 LBC, 22 receiving addresses (gap: 20), 10 change addresses (gap: 6), 0 channels, 0 certificates and 0 claims. 
2019-09-10 20:29:38,442 INFO     lbry.wallet.ledger:105: Loaded account bUDAFh958ePpL49PJF8z5E1KsZUHgcDuyC with 0.0 LBC, 20 receiving addresses (gap: 20), 6 change addresses (gap: 6), 0 channels, 0 certificates and 0 claims. 
2019-09-10 20:29:38,443 INFO     lbry.extras.daemon.Components:423: Starting the file manager
2019-09-10 20:29:38,452 INFO     lbry.stream.stream_manager:148: Initializing 0 files
2019-09-10 20:29:38,458 INFO     lbry.stream.stream_manager:163: Started stream manager with 0 files
2019-09-10 20:29:38,459 WARNING  lbry.stream.stream_manager:165: no DHT node given, resuming downloads trusting that we can contact reflector
2019-09-10 20:29:38,460 INFO     lbry.extras.daemon.Components:429: Done setting up file manager
2019-09-10 20:29:38,476 INFO     torba.client.basenetwork:304: connected to spv8.lbry.com:50001
2019-09-10 20:29:38,647 INFO     torba.client.basenetwork:304: connected to spv9.lbry.com:50001
2019-09-10 20:29:47,343 INFO     lbry.extras.daemon.Daemon:841: Get version info: {"processor": "", "python_version": "3.7.1", "platform": "Android 8.1.0 (API 27)", "os_release": "3.18.115-lineageos-g23d05f4", "os_system": "android", "lbrynet_version": "0.40.0", "torba_version": "0.5.7", "build": "release"}
2019-09-10 20:30:20,380 ERROR    lbry.extras.daemon.Daemon:590: error handling api request
Traceback (most recent call last):
  File "/data/user/0/io.lbry.browser/files/app/crystax_python/site-packages/lbry/extras/daemon/Daemon.py", line 582, in _process_rpc_call
    result = fn(self, *_args, **_kwargs)
  File "/data/user/0/io.lbry.browser/files/app/crystax_python/site-packages/lbry/extras/daemon/Daemon.py", line 70, in _inner
    raise ComponentStartConditionNotMet(err_msg)
lbry.error.ComponentStartConditionNotMet: your wallet is locked```

**Comment by tzarebczan** [comment]
Actually - just reproduced it....it gets introduced when the wallet sync'd is disabled/re-enabled in-app (https://github.com/lbryio/lbry-android/issues/675)
