### ISSUE TITLE
native-rewrite - Oops! Something went wrong. User Authenticated.

### ISSUE THREAD

**Issue by robfitz273k** [lbryio/lbry-android#881]
## The Issue

Trying to use a signed in account with the rewritten android app triggers a gson related exception.  If the account is synced with youtube, I assume it only effects synced accounts.

In app/src/main/java/io/lbry/browser/model/lbryinc/User.java the youtube_channels field is defined as a List of Strings, but the array contains a more complex data strcuture (couldn't find any public documentation just some github issues lbryio/lbry-desktop#2646). 

As a quick hack, I was able to get the app to work by just commenting out the youtube_channels field in User.java and rebuilding.

### Steps to reproduce
1. Download and install apk from build server (build-812_commit-82dc025).
2. Sign In to an existing LBRY account which has been synced with YouTube.
3. Click email link.
4. Any action results in Oops screen, same after trying to restart app.

### Actual behaviour
Oops screen.  Earlier builds had a generic application crash message.

## System Configuration
- Device: OnePlus 6
- Android version: Android 10

## Anything Else
logcat output for the oops
```
05-16 18:36:02.291  1011  1813 E io.lbry.browser.Main: App startup failed: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 324 path $.youtube_channels[0]
05-16 18:36:02.291  1011  1813 E io.lbry.browser.Main: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 324 path $.youtube_channels[0]
05-16 18:36:02.291  1011  1813 E io.lbry.browser.Main:  at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
05-16 18:36:02.291  1011  1813 E io.lbry.browser.Main:  at com.google.gson.Gson.fromJson(Gson.java:932)
05-16 18:36:02.291  1011  1813 E io.lbry.browser.Main:  at com.google.gson.Gson.fromJson(Gson.java:897)
05-16 18:36:02.291  1011  1813 E io.lbry.browser.Main:  at com.google.gson.Gson.fromJson(Gson.java:846)
05-16 18:36:02.291  1011  1813 E io.lbry.browser.Main:  at io.lbry.browser.utils.Lbryio.fetchCurrentUser(Lbryio.java:193)
05-16 18:36:02.291  1011  1813 E io.lbry.browser.Main:  at io.lbry.browser.utils.Lbryio.authenticate(Lbryio.java:238)
05-16 18:36:02.291  1011  1813 E io.lbry.browser.Main:  at io.lbry.browser.MainActivity$27.doInBackground(MainActivity.java:1744)
05-16 18:36:02.291  1011  1813 E io.lbry.browser.Main:  at io.lbry.browser.MainActivity$27.doInBackground(MainActivity.java:1694)
05-16 18:36:02.291  1011  1813 E io.lbry.browser.Main:  at android.os.AsyncTask$3.call(AsyncTask.java:378)
05-16 18:36:02.291  1011  1813 E io.lbry.browser.Main:  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
05-16 18:36:02.291  1011  1813 E io.lbry.browser.Main:  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
05-16 18:36:02.291  1011  1813 E io.lbry.browser.Main:  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
05-16 18:36:02.291  1011  1813 E io.lbry.browser.Main:  at java.lang.Thread.run(Thread.java:919)
05-16 18:36:02.291  1011  1813 E io.lbry.browser.Main: Caused by: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 324 path $.youtube_channels[0]
05-16 18:36:02.291  1011  1813 E io.lbry.browser.Main:  at com.google.gson.stream.JsonReader.nextString(JsonReader.java:826)
05-16 18:36:02.291  1011  1813 E io.lbry.browser.Main:  at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:402)
05-16 18:36:02.291  1011  1813 E io.lbry.browser.Main:  at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:390)
05-16 18:36:02.291  1011  1813 E io.lbry.browser.Main:  at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
05-16 18:36:02.291  1011  1813 E io.lbry.browser.Main:  at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
05-16 18:36:02.291  1011  1813 E io.lbry.browser.Main:  at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
05-16 18:36:02.291  1011  1813 E io.lbry.browser.Main:  at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
05-16 18:36:02.291  1011  1813 E io.lbry.browser.Main:  at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
05-16 18:36:02.291  1011  1813 E io.lbry.browser.Main:  ... 12 more
```

## Screenshots
![image](https://user-images.githubusercontent.com/17150855/82126115-7f08ca00-97a2-11ea-950f-4161da525fbc.png)

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by robfitz273k** [comment]
Can confirm this was fixed by commit 5eb35e3283e1695ac56c03a6056ce59572843a6e.
